### ISSUE TITLE
Access is allowed from event dispatch thread with IW lock only

### ISSUE THREAD

**Issue by richardwiden** [MikeSafonov/jenkins-linter-idea-plugin#74]
Access is allowed from event dispatch thread with IW lock only.

IntelliJ IDEA: 211.7442.40

```shell
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@37e9ec64
Current thread: Thread[ApplicationImpl pooled thread 16,4,Idea Thread Group] 1576375405
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 687791145
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1047)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1022)
	at com.intellij.ide.IdeEventQueue.lambda$new$3(IdeEventQueue.java:212)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:334)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.KeyboardFocusManager.firePropertyChange(KeyboardFocusManager.java:1499)
	at java.desktop/java.awt.KeyboardFocusManager.setGlobalPermanentFocusOwner(KeyboardFocusManager.java:795)
	at java.desktop/java.awt.Component.removeNotify(Component.java:7147)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2847)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4809)
	at com.intellij.ui.components.JBList.removeNotify(JBList.java:78)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2831)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4809)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2831)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4809)
	at java.desktop/java.awt.Container.removeAll(Container.java:1322)
	at com.github.mikesafonov.jenkins.linter.ui.LinterResponsePanel.setErrors(LinterResponsePanel.kt:37)
	at com.github.mikesafonov.jenkins.linter.PerformJenkinsLinterAction.handleSuccess(PerformJenkinsLinterAction.kt:77)
	at com.github.mikesafonov.jenkins.linter.PerformJenkinsLinterAction.access$handleSuccess(PerformJenkinsLinterAction.kt:19)
	at com.github.mikesafonov.jenkins.linter.PerformJenkinsLinterAction$actionPerformed$1$1.run(PerformJenkinsLinterAction.kt:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by MikeSafonov** [comment]
Greetings. Thanks for the issue. Please upgrade plugin to `0.5.1`
